name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Adicionar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # Adicionar o servidor ao known_hosts para evitar o prompt de confirmação da chave do servidor
          ssh-keyscan -H 192.168.1.51 >> ~/.ssh/known_hosts

      - name: Deploy no servidor local
        run: |
          ssh -i ~/.ssh/id_ed25519 vaio@192.168.1.51 "cd /c/Users/vaio/CICD/CICD && ./deploy.sh"
