name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Rodar apenas quando houver push na branch main
  pull_request:
    branches:
      - main  # Para pull requests na branch main

jobs:
  test:
    runs-on: ubuntu-latest  # Roda no Ubuntu

    steps:
      # Passo 1: Baixar o código do repositório
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Rodar os testes de integração ou verificação do código
      - name: Rodar testes
        run: |
          # Compilando o código Java (ajustar se necessário para o seu caso)
          javac -d out src/*.java   # Compila o código Java
          
          # Verifique se o comando de compilação falhou
          if [ $? -ne 0 ]; then
            echo "❌ Falha na compilação! Não é permitido fazer push!"
            exit 1  # Se falhar, sai com erro
          fi

          # Rodando testes (ajustar conforme sua estrutura de testes)
          java -cp out TestClass    # Substitua TestClass pela sua classe de teste, se necessário

          # Verificando se os testes passaram
          if [ $? -ne 0 ]; then
            echo "❌ Testes falharam. Não é permitido fazer push!"
            exit 1  # Se os testes falharem, sai com erro
          fi

      # Passo 3: Verificação se tudo passou, caso contrário não faz push
      - name: Verificar se os testes passaram
        run: |
          echo "✅ Testes passaram! Pode prosseguir com o commit."

  # O deploy não será executado se o job de teste falhar
  deploy:
    needs: test  # O job de deploy só vai rodar se o de testes passar
    runs-on: ubuntu-latest  # Roda no Ubuntu também

    steps:
      - name: Adicionar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo -e "Host local-server\n  HostName 192.168.1.51\n  User vaio\n  IdentityFile ~/.ssh/id_ed25519\n  StrictHostKeyChecking no" > ~/.ssh/config

      # Passo 4: Fazer o deploy no servidor local via SSH
      - name: Deploy no servidor local
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no vaio@192.168.1.51 "cd /c/Users/vaio/CICD/CICD && ./deploy.sh"
