name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Listar arquivos do projeto
        run: ls -R

      - name: Compilar código Java
        run: |
          mkdir -p out
          # Compilar todas as classes Java na pasta src
          javac -d out $(find src -name "*.java")
          
          # Se a compilação falhar, o processo será interrompido
          if [ $? -ne 0 ]; then
            echo "::error::Falha na compilação!"
            exit 1
          fi
          
          echo "✅ Código compilado com sucesso!"

