jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Baixar o código do repositório
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Rodar testes customizados (caso tenha um script de teste)
      - name: Rodar testes
        run: |
          ./run_tests.sh  # Substitua pelo comando que executa seus testes (se tiver um script de shell)
