name: Verificar Compilação Java

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Listar arquivos
        run: ls -R

      - name: Compilar código Java
        run: |
          mkdir -p out
          echo "Compilando arquivos..."
          javac -d out $(find src -name "*.java") || {
            echo "::error::Erro na compilação!"
            exit 1
          }

      - name: ✅ Sucesso
        run: echo "Código compilou com sucesso!"
