name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Rodar apenas quando houver push na branch main
  pull_request:
    branches:
      - main  # Para pull requests na branch main

jobs:
  check:
    runs-on: ubuntu-latest  # Roda no Ubuntu

    steps:
      # Passo 1: Baixar o código do repositório
      - name: Checkout do código
        uses: actions/checkout@v2

      # Passo 2: Verificar se o código Java compila (sem usar gradle ou maven)
      - name: Verificar se o código Java compila
        run: |
          # Compilar todos os arquivos Java em 'src'
          javac src/*.java
          
          # Verificar se a compilação foi bem-sucedida
          if [ $? -ne 0 ]; then
            echo "❌ Erros de compilação encontrados. Não é permitido fazer push!"
            exit 1
          else
            echo "✅ O código compila corretamente!"
          fi
