name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Instalar sshpass para usar senha no SSH
      - name: Instalar sshpass
        run: sudo apt-get install -y sshpass

      # Passo 2: Realizar deploy usando senha via sshpass
      - name: Deploy no servidor local
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no vaio@192.168.1.51 "cd /c/Users/vaio/CICD/CICD && ./deploy.sh"
