name: Verificar Compilação Java

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  verificar:
    name: Verificar Compilação Java
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Listar arquivos (debug)
        run: ls -R

      - name: Compilar código Java
        run: |
          mkdir -p out
          echo "Compilando arquivos..."
          if javac -d out $(find src -name "*.java"); then
            echo "✅ Compilação bem-sucedida."
          else
            echo "::error::Erro na compilação!"
            exit 1
          fi  # Corrigido aqui o fechamento do if

      - name: ✅ Sucesso
        if: success()
        run: echo "✅ Código compilou com sucesso!"
