name: CI/CD Local

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # <- roda no seu PC

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Rodar Deploy Script
      run: |
        cd C:/Users/seu_usuario/CICD
        ./deploy.sh
