name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  verificar_e_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Listar arquivos (debug)
        run: ls -R

      - name: Compilar código Java
        run: |
          mkdir -p out
          echo "Compilando arquivos..."
          if javac -d out $(find src -name "*.java"); then
            echo "✅ Compilação bem-sucedida."
          else
            echo "::error::Erro na compilação!"
            exit 1
          fi

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo -e "Host 192.168.108.56\nHostName 192.168.108.56\nUser vaio\nIdentityFile ~/.ssh/id_ed25519\nStrictHostKeyChecking no" > ~/.ssh/config

      - name: Deploy no servidor via SSH
        run: |
          ssh vaio@192.168.108.56 "cd /c/Users/vaio/CICD/CICD && ./deploy.sh"
